// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type MemberTableRow = {
    id: string;
    email: string;
    role: { id: string; displayField: string };
    status: "active" | "suspend";
    username: string;
    password: string;
    userRole: "kontributor" | "peserta";
    birthDate: Date;
    domicile: string;
    passwordShow: string;
  };

  type AllMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      status: "active" | "suspend";
      username: string;
      password: string;
      userRole: "kontributor" | "peserta";
      birthDate: Date;
      domicile: string;
      passwordShow: string;
    };
    write: {
      email: string;
      status: "active" | "suspend";
      username: string;
      password: string;
      userRole: "kontributor" | "peserta";
      birthDate: Date;
      domicile: string;
      passwordShow: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AuthDataViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      status: "active" | "suspend";
      username: string;
      password: string;
      passwordShow: string;
    };
    write: {
      email: string;
      status: "active" | "suspend";
      username: string;
      password: string;
      passwordShow: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type ProjectSchema = {
    allMember: AllMemberViewRow;
    authData: AuthDataViewRow;
  };
}
